name: ActiveCraft-Dashboard
version: '${project.version}'
main: de.cplaiz.activecraftdashboard.ActiveCraftDashboard
api-version: 1.17
authors: [ CPlaiz ]
depend: [ ActiveCraft-Core ]
softdepend: [ ActiveCraft-Discord ]
description: An elegant way to manage your server remotely.
libraries:
  - io.ktor:ktor-server-netty-jvm:2.0.2
  - io.ktor:ktor-server-core-jvm:2.0.2
  - io.ktor:ktor-server-content-negotiation-jvm:2.0.2
  - io.ktor:ktor-serialization-kotlinx-json-jvm:2.0.2
  - io.ktor:ktor-network-tls-certificates-jvm:2.0.2
  - org.jetbrains.exposed:exposed-core:0.38.2
  - org.jetbrains.exposed:exposed-dao:0.38.2
  - org.jetbrains.exposed:exposed-jdbc:0.38.2

commands:
  restart-http-server:
    description: Restart the HTTP server
    permission: activecraft.dashboard.httpserver.restart
  register-device:
    description: Register a device
    permission: activecraft.dashboard.device.register